# Generated by Django 5.0.3 on 2024-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
